### ISSUE TITLE
Standardize on a test configuration format

### ISSUE THREAD

**Issue by rajsite** [ni/VireoSDK#153]
Right now we have 2 formats for organizing tests represented in the repository

1. Tests organized by folder 
test-it/
test-it/Blacklist
test-it/x
test-it/ManualTests

2. Tests organized by test-it/testList.json configuration

Currently browser tests are configured by having karma serve test-it/*.via and jasmine disables specific tests in testSuite.js. This follows the conventions of karma and jasmine but it could be reconfigured to do either method proposed above.

Any preference for folder-based vs list-based configuration?

**Comment by rajsite** [comment]
I would prefer a mixture.
Tests go into folders based on feature
Test sets go into testList.json based on platforms. Glob patterns used to prevent having to modify configuration for every new test added.

ie
test-it/core
test-it/filesystem
test-it/manual
test-it/http

```json
testList.json
{
  "native": [
    "test-it/core/*.via",
    "test-it/filesystem/*.via"
  ],
  "node": [
    "test-it/core/*.via",
    "!test-it/core/specificTestDisabled.via"
  ],
  "browser": [
    "test-it/core/*.via",
    "test-it/http/*.via"
  ]
}
```

**Comment by cglzaguilar** [comment]
Sounds good, but I guess the core directory will contain most of the tests. It is worth it to subdivide core into arrays, strings and so for?

**Comment by sanmut** [comment]
Is there a way to just tag tests such that a test can have multiple tags. As the test suite develops, I have a feeling there might be some overlap of categories (either folder based or list based configuration) for tests and putting the tests in one category/folder might be more misleading than not categorizing them? This may not be a big concern if the categories are broad and coarse. I tend to intuitively like tags/labels where this problem can be avoided.

**Comment by rajsite** [comment]
Talked to @sanmut and it sounds like the json file proposed for picking tests out with paths, wildcards, and exceptions (ie !somefile.via) sounds good

The open question was the same as @cglzaguilar about how to organize tests. I'm going to propose organizing the tests corresponding to the src tree.

ie 
src/core
src/io

test-it/core
test-it/io
test-it/results/core
test-it/results/io
test-it/karma/jstests

@cglzaguilar and @sanmut any alternate proposals?

**Comment by sanmut** [comment]
That sounds good to me (core and io) and following source tree.

**Comment by spathiwa** [comment]
To me, 'core' is too coarse, and provides no benefit for organization because almost all of the Vireo language features are there.
Also, I prefer having a results folder inside each category, not at the top level.

**Comment by rajsite** [comment]
@spathiwa that's understandable, please provide a concrete alternative example 👍

**Comment by rajsite** [comment]
Unrelated to the VTR tets, but just for my reference, neat tag plugin for karma: https://www.npmjs.com/package/karma-jasmine-spec-tags

**Comment by rajsite** [comment]
As a note, being able to use the glob patterns (wild cards + exclusions) as described here: https://github.com/ni/VireoSDK/issues/153#issuecomment-271459888

May have helped with an issue here: https://travis-ci.org/ni/VireoSDK/builds/203994600

In that build the JS and Native tests passed but the karma test failed. This is because the new test was accidentally forgotten to be added to the testList.json file while the karma configuration wildcards included the test.

**Comment by rajsite** [comment]
We are in a better place now. Tests and results are in separate folders. And the browser and node runners both rely on testlist.json. We can make new issues for other test configuration deficiencies as needed.
