### ISSUE TITLE
Windows DST support incomplete

### ISSUE THREAD

**Issue by spathiwa** [ni/VireoSDK#218]
Date::getLocaletimeZone() needs to be extended on Windows to be able to set the timezoneoffset based on whether DST is in effect at a given/passed-in time, rather than the current time. 

This support has already been added for Linux/Mac/JS

**Comment by spathiwa** [comment]
I think this win32 api might be helpful:
https://msdn.microsoft.com/en-us/library/ms724949(VS.85).aspx

**Comment by sanmut** [comment]
https://github.com/ni/VireoSDK/commit/5c14df1a1061528ce8a975f2b1a15b0095f42527 (#230) fixes this issue. Closing.
