### ISSUE TITLE
Clean-up branches

### ISSUE THREAD

**Issue by rajsite** [ni/VireoSDK#240]
There are several stale branches that we can clean-up and settings we can toggle to prevent some issues. Here are the current branches and recommendations:

The following branches show that they are zero commits ahead of incoming. Since they have no new work they seem safe to delete:
- [x] public
- [x] dynamic-allocations
- [x] generics
- [x] queue_experiments
- [x] static_link

The following have some commits in them. I think we should tag these to preserve the commits and delete the branches (http://stackoverflow.com/questions/1307114/how-can-i-archive-git-branches)
- [x] micro_inwork
- [x] StaticLink2

The following are currently very important, we should enable branch protections (https://help.github.com/articles/about-protected-branches/) for them:
- [x] master

The master branch is currently not being utilized. We should investigate needed configuration changes to move to master as the primary branch:
- [x] Perform fast forward merge of incoming to master
- [x] Changing github default branch
- [x] Verify Travis configured
- [x] Verify npm configuration
- [x] Update badges in README
- [x] Delete incoming

**Comment by rajsite** [comment]
@funkmaster2 there is a branch called remove-http-warnings that looks like it was already merged into incoming, can we go ahead and delete this branch?

**Comment by spathiwa** [comment]
I'm for all of these suggestions, except I don't think we should delete master.

Actually, I'd like to merge incoming into master and make that our main branch like a normal sane project.

**Comment by sanmut** [comment]
I agree with Milan's comments and I agree with @spathiwa . We should not delete "master" but should try to start using that as typical git projects.

**Comment by rajsite** [comment]
Updated the issue to reflect migration back to master for primary branch

**Comment by rajsite** [comment]
all done!
