### ISSUE TITLE
Remove StringFormat and Scan prims w/o error I/O

### ISSUE THREAD

**Issue by spathiwa** [ni/VireoSDK#256]
See TODO in NumericString.cpp.

**Comment by rajsite** [comment]
@spathiwa can you provide a bit more detail and a link for this issue? There are several TODOs in that file.

**Comment by spathiwa** [comment]
Nah, I already have a PR in to fix this.

**Comment by rajsite** [comment]
👍

**Comment by rajsite** [comment]
closing because the PR went in
