### ISSUE TITLE
Bug in LICENSE.txt

### ISSUE THREAD

**Issue by JackDunaway** [ni/VireoSDK#28]
There seems to be a bug in LICENSE.txt that stems from Section 3a (https://github.com/ni/VireoSDK/blob/incoming/LICENSE.txt#L18-L19) that prevents us from running Vireo.

This issue might also affect young learners seeking jobs in our profession.

This issue manifests on all platforms.

Perhaps boilerplate `MIT license` could resolve this issue?

Promising platform, Vireo!

**Comment by rajsite** [comment]
+1

**Comment by PaulAustin** [comment]
Working on it :)

**Comment by wirebirdlabs** [comment]
> Working on it :)

Great to hear!

**Comment by JackDunaway** [comment]
Any news?

**Comment by rajsite** [comment]
@prestwick ❤️ 😄

**Comment by PaulAustin** [comment]
It's Github, make a pull request ;) . No, I guess that is one change you can't make even experimentally in your fork.  I can see lots of great work is going on. Glad to see it.

**Comment by rajsite** [comment]
Fixed the license! :D 🎉🎊

**Comment by PaulAustin** [comment]
Nice
