### ISSUE TITLE
CopyProcName intermittently returns different values between the first and second pass

### ISSUE THREAD

**Issue by cglzaguilar** [ni/VireoSDK#332]
CopyProcName is currently not being call until we root cause the issue and reenable the code. See comment in GenericFunctions.cpp

**Comment by spathiwa** [comment]
Please attach (intermittently-)reproducing via file here.

**Comment by cglzaguilar** [comment]
[CopyErrorSmallFor2.zip](https://github.com/ni/VireoSDK/files/1264093/CopyErrorSmallFor2.zip)

**Comment by cglzaguilar** [comment]
Closing issue, it has been already addressed.
