### ISSUE TITLE
Intermittent Build Failues

### ISSUE THREAD

**Issue by rajsite** [ni/VireoSDK#361]
Use this issue to track intermittent build failures.

Instructions:

1. Create a new issue and add a comment linking to it below with a summary.

   Make sure to add the full details in the linked issue and not in this tracking issue. Include details like pull request, CI, links to CI output, OS version, major changes, etc in the linked issue.

2. Immediately close the intermittent issue if it is not actively being tracked or updated at the moment.

   Re-open an issue / add more details if encountered and blocking work or if in work.

**Comment by rajsite** [comment]
timingtest2 is failing intermittently on firefox

From https://github.com/ni/VireoSDK/issues/345

**Comment by rajsite** [comment]
A Pull Request that was failing PhatomJS on AppVeyor consistently and could not figure out why. Eventually just created a new pull request with the same exact changes but everything passed:

https://github.com/ni/VireoSDK/issues/315

**Comment by rajsite** [comment]
AppVeyor showed what appears to be increased frequency of full build hangs (resulting in a timeout after 1 hr) after a change went in. It could be a fluke but not sure.

https://github.com/ni/VireoSDK/issues/363

**Comment by ggumen** [comment]
UserEventsMultiple test was intermittent on AppVeyor: #612

**Comment by rajsite** [comment]
Existing issues from Travis and AppVeyor, can track new issues separately as needed
