### ISSUE TITLE
Add Support for identifier paths with dynamic element (arrays) 

### ISSUE THREAD

**Issue by PaulAustin** [ni/VireoSDK#47]
The TM method GetSubElementAddressFromPath drills down an identifier path to determine the effective address of a value.  During code synthesis this method will not traverse path elements that can result in a dynamic target address. For example, the address of an array element can change if the array is resized. However methods used at runtime run time to read/write using identifier paths should allow dynamic paths.  Add this functionality.

**Comment by rajsite** [comment]
@spathiwa implemented this functionality
