### ISSUE TITLE
Introduce a first class type for Variant data type instead of just using TypeRef

### ISSUE THREAD

**Issue by sanmut** [ni/VireoSDK#547]
In [PR 545](https://github.com/ni/VireoSDK/pull/545), @spathiwa mentioned that having a global map of variant attributes keyed by the value is not good and recommended the variant should be a first class type (not just TypeRef) which owns its variant attribute map. We should refactor the Variant implementation to do this. This should not affect the APIs signature and thus may not require any DFIR /Via emission side changes.

**Comment by rajsite** [comment]
@sanmut was this fixed by #618 or is there any remaining work? If so we can update the issue, if not we can close it out.

**Comment by sanmut** [comment]
@rajsite, this was addressed partially by an earlier PR and completely addressed by PR #618. Closing it.
