### ISSUE TITLE
Example VIA in documentation does not run

### ISSUE THREAD

**Issue by jimkring** [ni/VireoSDK#686]
Hi!

I built Vireo into a native macOS executable\* and when I try to run `HelloWorld.via` I get the following error:

```shell
$ dist/esh HelloWorld.via
(Line 6 Error "Instruction not generated 'Print'.")
```

I'm not sure if this is a bug with Vireo or something that I did wrong on my end.

\*Note: I used the `make native` command as described in the [Build](https://github.com/ni/VireoSDK/blob/main/docs/Build.md) docs.

**Comment by jimkring** [comment]
More info...

  
When I try to run the Calculate.via example (on [IntroTypeExamples](https://github.com/ni/VireoSDK/blob/main/docs/IntroTypeExamples.md)), I get several errors for other instructions like `MulDouble` and `MulInt32`. 

```
// Calculate.via
define (CalcUsingIntegers  dv(.VirtualInstrument  (
   c(
       e(dv(Int32 6)  i)
       e(dv(Int32 7)  j)
       e(Int32  k)
   )
   clump(1
       MulInt32(i j k)
       Print(k)
   )
) ) )
define (CalcUsingDoubles  dv(.VirtualInstrument  (
   c(
       e(dv(Double 6)  x)
       e(dv(Double 7)  y)
       e(Double  z)
   )
   clump(1
       MulDouble(x y z)
       Print(z)
  )
) ) )
enqueue (CalcUsingIntegers)
enqueue (CalcUsingDoubles)
```

Here are the errors I get:

```shellsession
$ dist/esh Calculate.via
(Line 21 Error "Instruction not generated 'MulDouble'.")
(Line 22 Error "Instruction not generated 'Print'.")
(Line 9 Error "Instruction not generated 'MulInt32'.")
(Line 10 Error "Instruction not generated 'Print'.")
```

However, when I run CalculateGeneric.via I only get an error for the `Print` instruction, which means that the `Mul` instruction worked! That's good.

```
// CalculateGeneric.via
define (Calc  dv(.VirtualInstrument  (
   c(
       e(dv(Int32 6)  i)
       e(dv(Int32 7)  j)
       e(Int32  k)
       e(dv(Double 6.0)  x)
       e(dv(Double 7.0)  y)
       e(Double  z)
   )
   clump(1
       Mul(i j k)   // Will resolve to MulInt32 at load time
       Print(k)
       Mul(x y z)    // Will resolve to MulDouble at load time
       Print(k)
  )
) ) )
```

Here are the errors I get:

```shellsession
$ dist/esh CalculateGeneric.via
(Line 13 Error "Instruction not generated 'Print'.")
(Line 15 Error "Instruction not generated 'Print'.")
```

I'm not sure why some of these instructions are  working and others are producing an "Instruction not generated" error.

**Comment by jimkring** [comment]
It looks like Printf and Println (which both work) have superseded Print.  Might make sense to update the docs/examples

![image](https://user-images.githubusercontent.com/381432/124693685-b352b480-de94-11eb-86df-f676a1b9f5c4.png)

**Comment by rajsite** [comment]
Good catch! Updated the bug title to reflect that the doc examples are outdated.

**Comment by jimkring** [comment]
Thanks @rajsite. I created PR #687 with the required changes.

I hope I did that correctly and in accordance with the contributor guidelines and workflow (which I read and tried to follow)
